copyAll:
	cp ../resfiles/tad-drcTinyPen5_JMD/unit*_allTraj.png figures;
	cp ../resfiles/tad-drcTinyPen5_JMD/dis*.png figures;
	cp ../resfiles/tad-drcTinyPen5_JMD/trajDisSpaceOverlap_trajDisSpaceOverlap figures;
	cp  figures;
	cp  figures;
	cp  figures;
	cp  figures;

