copyAll:
	cp ../resfiles/tad-drcTinyPen1_JMD/unit1_allTraj_tad-drcTinyPen1_JMD.png figures;
	cp ../resfiles/tad-drcTinyPen1_JMD/tAD_trajSameSpace_tad-drcTinyPen1_JMD.png figures;
	cp ../resfiles/tad-drcTinyPen1_JMD/PCA_trajSameSpace_tad-drcTinyPen1_JMD.png figures;
	cp ../resfiles/tad-drcTinyPen1_JMD/trajDisSpaceOverlap_PCA_tad-drcTinyPen1_JMD.png figures;
	cp ../resfiles/tad-drcTinyPen1_JMD/validDtiPCA.png figures;

